/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef hbase_CONSTANTS_H
#define hbase_CONSTANTS_H

#include "hbase_types.h"

namespace com { namespace alibaba { namespace hbase { namespace thrift2 {

class hbaseConstants {
 public:
  hbaseConstants();

};

extern const hbaseConstants g_hbase_constants;

}}}} // namespace

#endif
