// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "THBaseService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::com::alibaba::hbase::thrift2;

class THBaseServiceHandler : virtual public THBaseServiceIf {
 public:
  THBaseServiceHandler() {
    // Your initialization goes here
  }

  /**
   * Test for the existence of columns in the table, as specified in the TGet.
   * 
   * @return true if the specified TGet matches one or more keys, false if not
   * 
   * @param table the table to check on
   * 
   * @param tget the TGet to check for
   */
  bool exists(const std::string& table, const TGet& tget) {
    // Your implementation goes here
    printf("exists\n");
  }

  /**
   * Test for the existence of columns in the table, as specified by the TGets.
   * 
   * This will return an array of booleans. Each value will be true if the related Get matches
   * one or more keys, false if not.
   * 
   * @param table the table to check on
   * 
   * @param tgets a list of TGets to check for
   */
  void existsAll(std::vector<bool> & _return, const std::string& table, const std::vector<TGet> & tgets) {
    // Your implementation goes here
    printf("existsAll\n");
  }

  /**
   * Method for getting data from a row.
   * 
   * If the row cannot be found an empty Result is returned.
   * This can be checked by the empty field of the TResult
   * 
   * @return the result
   * 
   * @param table the table to get from
   * 
   * @param tget the TGet to fetch
   */
  void get(TResult& _return, const std::string& table, const TGet& tget) {
    // Your implementation goes here
    printf("get\n");
  }

  /**
   * Method for getting multiple rows.
   * 
   * If a row cannot be found there will be a null
   * value in the result list for that TGet at the
   * same position.
   * 
   * So the Results are in the same order as the TGets.
   * 
   * @param table the table to get from
   * 
   * @param tgets a list of TGets to fetch, the Result list
   * will have the Results at corresponding positions
   * or null if there was an error
   */
  void getMultiple(std::vector<TResult> & _return, const std::string& table, const std::vector<TGet> & tgets) {
    // Your implementation goes here
    printf("getMultiple\n");
  }

  /**
   * Commit a TPut to a table.
   * 
   * @param table the table to put data in
   * 
   * @param tput the TPut to put
   */
  void put(const std::string& table, const TPut& tput) {
    // Your implementation goes here
    printf("put\n");
  }

  /**
   * Atomically checks if a row/family/qualifier value matches the expected
   * value. If it does, it adds the TPut.
   * 
   * @return true if the new put was executed, false otherwise
   * 
   * @param table to check in and put to
   * 
   * @param row row to check
   * 
   * @param family column family to check
   * 
   * @param qualifier column qualifier to check
   * 
   * @param value the expected value, if not provided the
   * check is for the non-existence of the
   * column in question
   * 
   * @param tput the TPut to put if the check succeeds
   */
  bool checkAndPut(const std::string& table, const std::string& row, const std::string& family, const std::string& qualifier, const std::string& value, const TPut& tput) {
    // Your implementation goes here
    printf("checkAndPut\n");
  }

  /**
   * Commit a List of Puts to the table.
   * 
   * @param table the table to put data in
   * 
   * @param tputs a list of TPuts to commit
   */
  void putMultiple(const std::string& table, const std::vector<TPut> & tputs) {
    // Your implementation goes here
    printf("putMultiple\n");
  }

  /**
   * Deletes as specified by the TDelete.
   * 
   * Note: "delete" is a reserved keyword and cannot be used in Thrift
   * thus the inconsistent naming scheme from the other functions.
   * 
   * @param table the table to delete from
   * 
   * @param tdelete the TDelete to delete
   */
  void deleteSingle(const std::string& table, const TDelete& tdelete) {
    // Your implementation goes here
    printf("deleteSingle\n");
  }

  /**
   * Bulk commit a List of TDeletes to the table.
   * 
   * Throws a TIOError if any of the deletes fail.
   * 
   * Always returns an empty list for backwards compatibility.
   * 
   * @param table the table to delete from
   * 
   * @param tdeletes list of TDeletes to delete
   */
  void deleteMultiple(std::vector<TDelete> & _return, const std::string& table, const std::vector<TDelete> & tdeletes) {
    // Your implementation goes here
    printf("deleteMultiple\n");
  }

  /**
   * Atomically checks if a row/family/qualifier value matches the expected
   * value. If it does, it adds the delete.
   * 
   * @return true if the new delete was executed, false otherwise
   * 
   * @param table to check in and delete from
   * 
   * @param row row to check
   * 
   * @param family column family to check
   * 
   * @param qualifier column qualifier to check
   * 
   * @param value the expected value, if not provided the
   * check is for the non-existence of the
   * column in question
   * 
   * @param tdelete the TDelete to execute if the check succeeds
   */
  bool checkAndDelete(const std::string& table, const std::string& row, const std::string& family, const std::string& qualifier, const std::string& value, const TDelete& tdelete) {
    // Your implementation goes here
    printf("checkAndDelete\n");
  }

  void increment(TResult& _return, const std::string& table, const TIncrement& tincrement) {
    // Your implementation goes here
    printf("increment\n");
  }

  void append(TResult& _return, const std::string& table, const TAppend& tappend) {
    // Your implementation goes here
    printf("append\n");
  }

  /**
   * Get a Scanner for the provided TScan object.
   * 
   * @return Scanner Id to be used with other scanner procedures
   * 
   * @param table the table to get the Scanner for
   * 
   * @param tscan the scan object to get a Scanner for
   */
  int32_t openScanner(const std::string& table, const TScan& tscan) {
    // Your implementation goes here
    printf("openScanner\n");
  }

  /**
   * Grabs multiple rows from a Scanner.
   * 
   * @return Between zero and numRows TResults
   * 
   * @param scannerId the Id of the Scanner to return rows from. This is an Id returned from the openScanner function.
   * 
   * @param numRows number of rows to return
   */
  void getScannerRows(std::vector<TResult> & _return, const int32_t scannerId, const int32_t numRows) {
    // Your implementation goes here
    printf("getScannerRows\n");
  }

  /**
   * Closes the scanner. Should be called to free server side resources timely.
   * Typically close once the scanner is not needed anymore, i.e. after looping
   * over it to get all the required rows.
   * 
   * @param scannerId the Id of the Scanner to close *
   */
  void closeScanner(const int32_t scannerId) {
    // Your implementation goes here
    printf("closeScanner\n");
  }

  /**
   * mutateRow performs multiple mutations atomically on a single row.
   * 
   * @param table table to apply the mutations
   * 
   * @param trowMutations mutations to apply
   */
  void mutateRow(const std::string& table, const TRowMutations& trowMutations) {
    // Your implementation goes here
    printf("mutateRow\n");
  }

  /**
   * Get results for the provided TScan object.
   * This helper function opens a scanner, get the results and close the scanner.
   * 
   * @return between zero and numRows TResults
   * 
   * @param table the table to get the Scanner for
   * 
   * @param tscan the scan object to get a Scanner for
   * 
   * @param numRows number of rows to return
   */
  void getScannerResults(std::vector<TResult> & _return, const std::string& table, const TScan& tscan, const int32_t numRows) {
    // Your implementation goes here
    printf("getScannerResults\n");
  }

  /**
   * Given a table and a row get the location of the region that
   * would contain the given row key.
   * 
   * reload = true means the cache will be cleared and the location
   * will be fetched from meta.
   * 
   * @param table
   * @param row
   * @param reload
   */
  void getRegionLocation(THRegionLocation& _return, const std::string& table, const std::string& row, const bool reload) {
    // Your implementation goes here
    printf("getRegionLocation\n");
  }

  /**
   * Get all of the region locations for a given table.
   * 
   * 
   * @param table
   */
  void getAllRegionLocations(std::vector<THRegionLocation> & _return, const std::string& table) {
    // Your implementation goes here
    printf("getAllRegionLocations\n");
  }

  /**
   * Atomically checks if a row/family/qualifier value matches the expected
   * value. If it does, it mutates the row.
   * 
   * @return true if the row was mutated, false otherwise
   * 
   * @param table to check in and delete from
   * 
   * @param row row to check
   * 
   * @param family column family to check
   * 
   * @param qualifier column qualifier to check
   * 
   * @param compareOp comparison to make on the value
   * 
   * @param value the expected value to be compared against, if not provided the
   * check is for the non-existence of the column in question
   * 
   * @param rowMutations row mutations to execute if the value matches
   */
  bool checkAndMutate(const std::string& table, const std::string& row, const std::string& family, const std::string& qualifier, const TCompareOp::type compareOp, const std::string& value, const TRowMutations& rowMutations) {
    // Your implementation goes here
    printf("checkAndMutate\n");
  }

  /**
   * Get a table descriptor.
   * @return the TableDescriptor of the giving tablename
   * 
   * 
   * @param table the tablename of the table to get tableDescriptor
   */
  void getTableDescriptor(TTableDescriptor& _return, const TTableName& table) {
    // Your implementation goes here
    printf("getTableDescriptor\n");
  }

  /**
   * Get table descriptors of tables.
   * @return the TableDescriptor of the giving tablename
   * 
   * 
   * @param tables the tablename list of the tables to get tableDescriptor
   */
  void getTableDescriptors(std::vector<TTableDescriptor> & _return, const std::vector<TTableName> & tables) {
    // Your implementation goes here
    printf("getTableDescriptors\n");
  }

  /**
   * 
   * @return true if table exists already, false if not
   * 
   * 
   * @param tableName the tablename of the tables to check
   */
  bool tableExists(const TTableName& tableName) {
    // Your implementation goes here
    printf("tableExists\n");
  }

  /**
   * Get table descriptors of tables that match the given pattern
   * @return the tableDescriptors of the matching table
   * 
   * 
   * @param regex The regular expression to match against
   * 
   * @param includeSysTables set to false if match only against userspace tables
   */
  void getTableDescriptorsByPattern(std::vector<TTableDescriptor> & _return, const std::string& regex, const bool includeSysTables) {
    // Your implementation goes here
    printf("getTableDescriptorsByPattern\n");
  }

  /**
   * Get table descriptors of tables in the given namespace
   * @return the tableDescriptors in the namespce
   * 
   * 
   * @param name The namesapce's name
   */
  void getTableDescriptorsByNamespace(std::vector<TTableDescriptor> & _return, const std::string& name) {
    // Your implementation goes here
    printf("getTableDescriptorsByNamespace\n");
  }

  /**
   * Get table names of tables that match the given pattern
   * @return the table names of the matching table
   * 
   * 
   * @param regex The regular expression to match against
   * 
   * @param includeSysTables set to false if match only against userspace tables
   */
  void getTableNamesByPattern(std::vector<TTableName> & _return, const std::string& regex, const bool includeSysTables) {
    // Your implementation goes here
    printf("getTableNamesByPattern\n");
  }

  /**
   * Get table names of tables in the given namespace
   * @return the table names of the matching table
   * 
   * 
   * @param name The namesapce's name
   */
  void getTableNamesByNamespace(std::vector<TTableName> & _return, const std::string& name) {
    // Your implementation goes here
    printf("getTableNamesByNamespace\n");
  }

  /**
   * Creates a new table with an initial set of empty regions defined by the specified split keys.
   * The total number of regions created will be the number of split keys plus one. Synchronous
   * operation.
   * 
   * 
   * @param desc table descriptor for table
   * 
   * @param splitKeys rray of split keys for the initial regions of the table
   */
  void createTable(const TTableDescriptor& desc, const std::vector<std::string> & splitKeys) {
    // Your implementation goes here
    printf("createTable\n");
  }

  /**
   * Deletes a table. Synchronous operation.
   * 
   * 
   * @param tableName the tablename to delete
   */
  void deleteTable(const TTableName& tableName) {
    // Your implementation goes here
    printf("deleteTable\n");
  }

  /**
   * Truncate a table. Synchronous operation.
   * 
   * 
   * @param tableName the tablename to truncate
   * 
   * @param preserveSplits whether to  preserve previous splits
   */
  void truncateTable(const TTableName& tableName, const bool preserveSplits) {
    // Your implementation goes here
    printf("truncateTable\n");
  }

  /**
   * Enalbe a table
   * 
   * 
   * @param tableName the tablename to enable
   */
  void enableTable(const TTableName& tableName) {
    // Your implementation goes here
    printf("enableTable\n");
  }

  /**
   * Disable a table
   * 
   * 
   * @param tableName the tablename to disable
   */
  void disableTable(const TTableName& tableName) {
    // Your implementation goes here
    printf("disableTable\n");
  }

  /**
   * 
   * @return true if table is enabled, false if not
   * 
   * 
   * @param tableName the tablename to check
   */
  bool isTableEnabled(const TTableName& tableName) {
    // Your implementation goes here
    printf("isTableEnabled\n");
  }

  /**
   * 
   * @return true if table is disabled, false if not
   * 
   * 
   * @param tableName the tablename to check
   */
  bool isTableDisabled(const TTableName& tableName) {
    // Your implementation goes here
    printf("isTableDisabled\n");
  }

  /**
   * 
   * @return true if table is available, false if not
   * 
   * 
   * @param tableName the tablename to check
   */
  bool isTableAvailable(const TTableName& tableName) {
    // Your implementation goes here
    printf("isTableAvailable\n");
  }

  /**
   *  * Use this api to check if the table has been created with the specified number of splitkeys
   *  * which was used while creating the given table. Note : If this api is used after a table's
   *  * region gets splitted, the api may return false.
   *  *
   *  * @return true if table is available, false if not
   * *
   * 
   * @param tableName the tablename to check
   * 
   * @param splitKeys keys to check if the table has been created with all split keys
   */
  bool isTableAvailableWithSplit(const TTableName& tableName, const std::vector<std::string> & splitKeys) {
    // Your implementation goes here
    printf("isTableAvailableWithSplit\n");
  }

  /**
   * Add a column family to an existing table. Synchronous operation.
   * 
   * 
   * @param tableName the tablename to add column family to
   * 
   * @param column column family descriptor of column family to be added
   */
  void addColumnFamily(const TTableName& tableName, const TColumnFamilyDescriptor& column) {
    // Your implementation goes here
    printf("addColumnFamily\n");
  }

  /**
   * Delete a column family from a table. Synchronous operation.
   * 
   * 
   * @param tableName the tablename to delete column family from
   * 
   * @param column name of column family to be deleted
   */
  void deleteColumnFamily(const TTableName& tableName, const std::string& column) {
    // Your implementation goes here
    printf("deleteColumnFamily\n");
  }

  /**
   * Modify an existing column family on a table. Synchronous operation.
   * 
   * 
   * @param tableName the tablename to modify column family
   * 
   * @param column column family descriptor of column family to be modified
   */
  void modifyColumnFamily(const TTableName& tableName, const TColumnFamilyDescriptor& column) {
    // Your implementation goes here
    printf("modifyColumnFamily\n");
  }

  /**
   * Modify an existing table
   * 
   * 
   * @param desc the descriptor of the table to modify
   */
  void modifyTable(const TTableDescriptor& desc) {
    // Your implementation goes here
    printf("modifyTable\n");
  }

  /**
   * Create a new namespace. Blocks until namespace has been successfully created or an exception is
   * thrown
   * 
   * 
   * @param namespaceDesc descriptor which describes the new namespace
   */
  void createNamespace(const TNamespaceDescriptor& namespaceDesc) {
    // Your implementation goes here
    printf("createNamespace\n");
  }

  /**
   * Modify an existing namespace.  Blocks until namespace has been successfully modified or an
   * exception is thrown
   * 
   * 
   * @param namespaceDesc descriptor which describes the new namespace
   */
  void modifyNamespace(const TNamespaceDescriptor& namespaceDesc) {
    // Your implementation goes here
    printf("modifyNamespace\n");
  }

  /**
   * Delete an existing namespace. Only empty namespaces (no tables) can be removed.
   * Blocks until namespace has been successfully deleted or an
   * exception is thrown.
   * 
   * 
   * @param name namespace name
   */
  void deleteNamespace(const std::string& name) {
    // Your implementation goes here
    printf("deleteNamespace\n");
  }

  /**
   * Get a namespace descriptor by name.
   * @retrun the descriptor
   * 
   * 
   * @param name name of namespace descriptor
   */
  void getNamespaceDescriptor(TNamespaceDescriptor& _return, const std::string& name) {
    // Your implementation goes here
    printf("getNamespaceDescriptor\n");
  }

  /**
   * @return all namespaces
   * 
   */
  void listNamespaceDescriptors(std::vector<TNamespaceDescriptor> & _return) {
    // Your implementation goes here
    printf("listNamespaceDescriptors\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::apache::thrift::stdcxx::shared_ptr<THBaseServiceHandler> handler(new THBaseServiceHandler());
  ::apache::thrift::stdcxx::shared_ptr<TProcessor> processor(new THBaseServiceProcessor(handler));
  ::apache::thrift::stdcxx::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::apache::thrift::stdcxx::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::apache::thrift::stdcxx::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

