<?php
/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * Thrift wrapper around
 * org.apache.hadoop.hbase.io.compress.Algorithm
 */
final class TCompressionAlgorithm
{
    const LZO = 0;

    const GZ = 1;

    const NONE = 2;

    const SNAPPY = 3;

    const LZ4 = 4;

    const BZIP2 = 5;

    const ZSTD = 6;

    static public $__names = array(
        0 => 'LZO',
        1 => 'GZ',
        2 => 'NONE',
        3 => 'SNAPPY',
        4 => 'LZ4',
        5 => 'BZIP2',
        6 => 'ZSTD',
    );
}

