<?php
/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * Thrift wrapper around
 * org.apache.hadoop.hbase.filter.CompareFilter$CompareOp.
 */
final class TCompareOp
{
    const LESS = 0;

    const LESS_OR_EQUAL = 1;

    const EQUAL = 2;

    const NOT_EQUAL = 3;

    const GREATER_OR_EQUAL = 4;

    const GREATER = 5;

    const NO_OP = 6;

    static public $__names = array(
        0 => 'LESS',
        1 => 'LESS_OR_EQUAL',
        2 => 'EQUAL',
        3 => 'NOT_EQUAL',
        4 => 'GREATER_OR_EQUAL',
        5 => 'GREATER',
        6 => 'NO_OP',
    );
}

