<?php
/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * Thrift wrapper around
 * org.apache.hadoop.hbase.io.encoding.DataBlockEncoding
 */
final class TDataBlockEncoding
{
    /**
     * Disable data block encoding.
     */
    const NONE = 0;

    const PREFIX = 2;

    const DIFF = 3;

    const FAST_DIFF = 4;

    const ROW_INDEX_V1 = 7;

    static public $__names = array(
        0 => 'NONE',
        2 => 'PREFIX',
        3 => 'DIFF',
        4 => 'FAST_DIFF',
        7 => 'ROW_INDEX_V1',
    );
}

