<?php
/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

/**
 * Specify Durability:
 *  - SKIP_WAL means do not write the Mutation to the WAL.
 *  - ASYNC_WAL means write the Mutation to the WAL asynchronously,
 *  - SYNC_WAL means write the Mutation to the WAL synchronously,
 *  - FSYNC_WAL means Write the Mutation to the WAL synchronously and force the entries to disk.
 */
final class TDurability
{
    const USE_DEFAULT = 0;

    const SKIP_WAL = 1;

    const ASYNC_WAL = 2;

    const SYNC_WAL = 3;

    const FSYNC_WAL = 4;

    static public $__names = array(
        0 => 'USE_DEFAULT',
        1 => 'SKIP_WAL',
        2 => 'ASYNC_WAL',
        3 => 'SYNC_WAL',
        4 => 'FSYNC_WAL',
    );
}

