<?php
/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class THRegionLocation
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'serverName',
            'isRequired' => true,
            'type' => TType::STRUCT,
            'class' => '\TServerName',
        ),
        2 => array(
            'var' => 'regionInfo',
            'isRequired' => true,
            'type' => TType::STRUCT,
            'class' => '\THRegionInfo',
        ),
    );

    /**
     * @var \TServerName
     */
    public $serverName = null;
    /**
     * @var \THRegionInfo
     */
    public $regionInfo = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['serverName'])) {
                $this->serverName = $vals['serverName'];
            }
            if (isset($vals['regionInfo'])) {
                $this->regionInfo = $vals['regionInfo'];
            }
        }
    }

    public function getName()
    {
        return 'THRegionLocation';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRUCT) {
                        $this->serverName = new \TServerName();
                        $xfer += $this->serverName->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRUCT) {
                        $this->regionInfo = new \THRegionInfo();
                        $xfer += $this->regionInfo->read($input);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('THRegionLocation');
        if ($this->serverName !== null) {
            if (!is_object($this->serverName)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('serverName', TType::STRUCT, 1);
            $xfer += $this->serverName->write($output);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->regionInfo !== null) {
            if (!is_object($this->regionInfo)) {
                throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
            }
            $xfer += $output->writeFieldBegin('regionInfo', TType::STRUCT, 2);
            $xfer += $this->regionInfo->write($output);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
