<?php
/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class TServerName
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'hostName',
            'isRequired' => true,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'port',
            'isRequired' => false,
            'type' => TType::I32,
        ),
        3 => array(
            'var' => 'startCode',
            'isRequired' => false,
            'type' => TType::I64,
        ),
    );

    /**
     * @var string
     */
    public $hostName = null;
    /**
     * @var int
     */
    public $port = null;
    /**
     * @var int
     */
    public $startCode = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['hostName'])) {
                $this->hostName = $vals['hostName'];
            }
            if (isset($vals['port'])) {
                $this->port = $vals['port'];
            }
            if (isset($vals['startCode'])) {
                $this->startCode = $vals['startCode'];
            }
        }
    }

    public function getName()
    {
        return 'TServerName';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->hostName);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::I32) {
                        $xfer += $input->readI32($this->port);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::I64) {
                        $xfer += $input->readI64($this->startCode);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('TServerName');
        if ($this->hostName !== null) {
            $xfer += $output->writeFieldBegin('hostName', TType::STRING, 1);
            $xfer += $output->writeString($this->hostName);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->port !== null) {
            $xfer += $output->writeFieldBegin('port', TType::I32, 2);
            $xfer += $output->writeI32($this->port);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->startCode !== null) {
            $xfer += $output->writeFieldBegin('startCode', TType::I64, 3);
            $xfer += $output->writeI64($this->startCode);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
